### ISSUE TITLE
Small request for moving tabs

### ISSUE THREAD

**Issue by mikhoul** [akhaku/tabulator#2]
I really like this extension and I will make an official fork that instead of opening the GUI only with a new tab will open it when we click on the button in the toolbar, it suit better my workflow. 

My request is to add the possibility to move the tabs around with drag and drop, if I was better with JS I would do it myself but I don't have enough knowledge to do that.

If you want to look at another extension that do that to see the strategy used  the old "[Tabspane](https://github.com/achekulaev/tabspane)" extension do that but poorly do the screenshot and seem abandoned.

Regards :octocat:

**Comment by akhaku** [comment]
Agreed, that's on my list, to add support for moving via drag and drop. Was kind of hoping to add "pinned" tab support first though, since pinned tabs are always grouped together at the start of their list. Maybe next weekend, now that I know it's more than just me that wants this?

**Comment by mikhoul** [comment]
Hi @akhaku ,

I was browsing the code to have abetter understanding of how it work and I see that you use  
`onActiveChanged` to take the screenshot and I was asking to myself if there is a reason why you don't use `onActivated` since  `onActiveChanged` is deprecated ? 🤔

Regards :octocat:

**Comment by mikhoul** [comment]
I would not even know how to make such extension in JS since I don't have enough knowledge in JS .

I was looking at the API available to try to find an easy way to screenshot the discarded tabs (so far no results here) and that's why I've see the event was deprecated, but I though "maybe the old vent had more granularity and that's why it was used instead of the new event". 


Regards :octocat:

**Comment by akhaku** [comment]
Implemented and released with v1.1.0. You'll need to click and hold before dragging. Feedback on the UX of dragging and dropping is welcome.

**Comment by mikhoul** [comment]
@akhaku  I would lower the delay that we have to hold before dragging to make it more "snappy" by 50% at least. 

Regards :octocat:

**Comment by akhaku** [comment]
It's at 200ms right now - sure, can tweak it down to 100 and see how it feels

**Comment by mikhoul** [comment]
I will test it ! :+1:
